"""MessageSMS model created

Revision ID: 0454d981bf03
Revises: e7561e1552fe
Create Date: 2025-01-17 05:58:11.170864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0454d981bf03'
down_revision = 'e7561e1552fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_sms',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(length=255), nullable=False),
    sa.Column('to', sa.String(length=20), nullable=False),
    sa.Column('from_', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_sms')
    # ### end Alembic commands ###
